version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: quiz_pg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quiz_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: quiz_redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
