// Code generated by MockGen. DO NOT EDIT.
// Source: db\repositories\interfaces.go
//
// Generated by this command:
//
//	mockgen -source=db\repositories\interfaces.go -destination=db\repositories\mocks\mock_repo.go
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	entities "quiz/entities/db"
	dto "quiz/entities/dto"
	reflect "reflect"
	time "time"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockQuizRepository is a mock of QuizRepository interface.
type MockQuizRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuizRepositoryMockRecorder
	isgomock struct{}
}

// MockQuizRepositoryMockRecorder is the mock recorder for MockQuizRepository.
type MockQuizRepositoryMockRecorder struct {
	mock *MockQuizRepository
}

// NewMockQuizRepository creates a new mock instance.
func NewMockQuizRepository(ctrl *gomock.Controller) *MockQuizRepository {
	mock := &MockQuizRepository{ctrl: ctrl}
	mock.recorder = &MockQuizRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuizRepository) EXPECT() *MockQuizRepositoryMockRecorder {
	return m.recorder
}

// CreateQuiz mocks base method.
func (m *MockQuizRepository) CreateQuiz(ctx context.Context, quiz_name, quiz_description string, userID int) (entities.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuiz", ctx, quiz_name, quiz_description, userID)
	ret0, _ := ret[0].(entities.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuiz indicates an expected call of CreateQuiz.
func (mr *MockQuizRepositoryMockRecorder) CreateQuiz(ctx, quiz_name, quiz_description, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuiz", reflect.TypeOf((*MockQuizRepository)(nil).CreateQuiz), ctx, quiz_name, quiz_description, userID)
}

// DeleteQuiz mocks base method.
func (m *MockQuizRepository) DeleteQuiz(ctx context.Context, quizID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuiz", ctx, quizID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuiz indicates an expected call of DeleteQuiz.
func (mr *MockQuizRepositoryMockRecorder) DeleteQuiz(ctx, quizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuiz", reflect.TypeOf((*MockQuizRepository)(nil).DeleteQuiz), ctx, quizID)
}

// GetQuiz mocks base method.
func (m *MockQuizRepository) GetQuiz(ctx context.Context) ([]entities.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuiz", ctx)
	ret0, _ := ret[0].([]entities.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuiz indicates an expected call of GetQuiz.
func (mr *MockQuizRepositoryMockRecorder) GetQuiz(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuiz", reflect.TypeOf((*MockQuizRepository)(nil).GetQuiz), ctx)
}

// GetQuizByID mocks base method.
func (m *MockQuizRepository) GetQuizByID(ctx context.Context, quizID int) (entities.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuizByID", ctx, quizID)
	ret0, _ := ret[0].(entities.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuizByID indicates an expected call of GetQuizByID.
func (mr *MockQuizRepositoryMockRecorder) GetQuizByID(ctx, quizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuizByID", reflect.TypeOf((*MockQuizRepository)(nil).GetQuizByID), ctx, quizID)
}

// UpdateQuiz mocks base method.
func (m *MockQuizRepository) UpdateQuiz(ctx context.Context, quizID int, name, description *string) (entities.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuiz", ctx, quizID, name, description)
	ret0, _ := ret[0].(entities.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuiz indicates an expected call of UpdateQuiz.
func (mr *MockQuizRepositoryMockRecorder) UpdateQuiz(ctx, quizID, name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuiz", reflect.TypeOf((*MockQuizRepository)(nil).UpdateQuiz), ctx, quizID, name, description)
}

// MockQuestionRepository is a mock of QuestionRepository interface.
type MockQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepositoryMockRecorder
	isgomock struct{}
}

// MockQuestionRepositoryMockRecorder is the mock recorder for MockQuestionRepository.
type MockQuestionRepositoryMockRecorder struct {
	mock *MockQuestionRepository
}

// NewMockQuestionRepository creates a new mock instance.
func NewMockQuestionRepository(ctrl *gomock.Controller) *MockQuestionRepository {
	mock := &MockQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepository) EXPECT() *MockQuestionRepositoryMockRecorder {
	return m.recorder
}

// CheckIfQuestionOwner mocks base method.
func (m *MockQuestionRepository) CheckIfQuestionOwner(ctx context.Context, questionID, userID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfQuestionOwner", ctx, questionID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfQuestionOwner indicates an expected call of CheckIfQuestionOwner.
func (mr *MockQuestionRepositoryMockRecorder) CheckIfQuestionOwner(ctx, questionID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfQuestionOwner", reflect.TypeOf((*MockQuestionRepository)(nil).CheckIfQuestionOwner), ctx, questionID, userID)
}

// CheckIfQuizOwner mocks base method.
func (m *MockQuestionRepository) CheckIfQuizOwner(ctx context.Context, quizID, userID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfQuizOwner", ctx, quizID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfQuizOwner indicates an expected call of CheckIfQuizOwner.
func (mr *MockQuestionRepositoryMockRecorder) CheckIfQuizOwner(ctx, quizID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfQuizOwner", reflect.TypeOf((*MockQuestionRepository)(nil).CheckIfQuizOwner), ctx, quizID, userID)
}

// CreateQuestion mocks base method.
func (m *MockQuestionRepository) CreateQuestion(ctx context.Context, tx any, quizID int, data dto.CreateQuestionDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuestion", ctx, tx, quizID, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuestion indicates an expected call of CreateQuestion.
func (mr *MockQuestionRepositoryMockRecorder) CreateQuestion(ctx, tx, quizID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestion", reflect.TypeOf((*MockQuestionRepository)(nil).CreateQuestion), ctx, tx, quizID, data)
}

// DeleteQuestion mocks base method.
func (m *MockQuestionRepository) DeleteQuestion(ctx context.Context, questionID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuestion", ctx, questionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuestion indicates an expected call of DeleteQuestion.
func (mr *MockQuestionRepositoryMockRecorder) DeleteQuestion(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuestion", reflect.TypeOf((*MockQuestionRepository)(nil).DeleteQuestion), ctx, questionID)
}

// GetQuestion mocks base method.
func (m *MockQuestionRepository) GetQuestion(ctx context.Context, questionID int) (entities.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestion", ctx, questionID)
	ret0, _ := ret[0].(entities.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestion indicates an expected call of GetQuestion.
func (mr *MockQuestionRepositoryMockRecorder) GetQuestion(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestion", reflect.TypeOf((*MockQuestionRepository)(nil).GetQuestion), ctx, questionID)
}

// GetQuestionIDsByQuizID mocks base method.
func (m *MockQuestionRepository) GetQuestionIDsByQuizID(ctx context.Context, quizID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionIDsByQuizID", ctx, quizID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionIDsByQuizID indicates an expected call of GetQuestionIDsByQuizID.
func (mr *MockQuestionRepositoryMockRecorder) GetQuestionIDsByQuizID(ctx, quizID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionIDsByQuizID", reflect.TypeOf((*MockQuestionRepository)(nil).GetQuestionIDsByQuizID), ctx, quizID)
}

// GetQuizQuestions mocks base method.
func (m *MockQuestionRepository) GetQuizQuestions(ctx context.Context, id int) ([]entities.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuizQuestions", ctx, id)
	ret0, _ := ret[0].([]entities.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuizQuestions indicates an expected call of GetQuizQuestions.
func (mr *MockQuestionRepositoryMockRecorder) GetQuizQuestions(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuizQuestions", reflect.TypeOf((*MockQuestionRepository)(nil).GetQuizQuestions), ctx, id)
}

// UpdateQuestion mocks base method.
func (m *MockQuestionRepository) UpdateQuestion(ctx context.Context, questionID int, data dto.UpdateQuestionDTO) (entities.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestion", ctx, questionID, data)
	ret0, _ := ret[0].(entities.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuestion indicates an expected call of UpdateQuestion.
func (mr *MockQuestionRepositoryMockRecorder) UpdateQuestion(ctx, questionID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestion", reflect.TypeOf((*MockQuestionRepository)(nil).UpdateQuestion), ctx, questionID, data)
}

// MockAnswerRepository is a mock of AnswerRepository interface.
type MockAnswerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnswerRepositoryMockRecorder
	isgomock struct{}
}

// MockAnswerRepositoryMockRecorder is the mock recorder for MockAnswerRepository.
type MockAnswerRepositoryMockRecorder struct {
	mock *MockAnswerRepository
}

// NewMockAnswerRepository creates a new mock instance.
func NewMockAnswerRepository(ctrl *gomock.Controller) *MockAnswerRepository {
	mock := &MockAnswerRepository{ctrl: ctrl}
	mock.recorder = &MockAnswerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnswerRepository) EXPECT() *MockAnswerRepositoryMockRecorder {
	return m.recorder
}

// CheckAnswer mocks base method.
func (m *MockAnswerRepository) CheckAnswer(ctx context.Context, questionID, answerID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAnswer", ctx, questionID, answerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAnswer indicates an expected call of CheckAnswer.
func (mr *MockAnswerRepositoryMockRecorder) CheckAnswer(ctx, questionID, answerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAnswer", reflect.TypeOf((*MockAnswerRepository)(nil).CheckAnswer), ctx, questionID, answerID)
}

// CheckIfAnswerOwner mocks base method.
func (m *MockAnswerRepository) CheckIfAnswerOwner(ctx context.Context, answerID, userID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfAnswerOwner", ctx, answerID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfAnswerOwner indicates an expected call of CheckIfAnswerOwner.
func (mr *MockAnswerRepositoryMockRecorder) CheckIfAnswerOwner(ctx, answerID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfAnswerOwner", reflect.TypeOf((*MockAnswerRepository)(nil).CheckIfAnswerOwner), ctx, answerID, userID)
}

// CheckIfQuestionOwner mocks base method.
func (m *MockAnswerRepository) CheckIfQuestionOwner(ctx context.Context, questionID, userID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfQuestionOwner", ctx, questionID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfQuestionOwner indicates an expected call of CheckIfQuestionOwner.
func (mr *MockAnswerRepositoryMockRecorder) CheckIfQuestionOwner(ctx, questionID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfQuestionOwner", reflect.TypeOf((*MockAnswerRepository)(nil).CheckIfQuestionOwner), ctx, questionID, userID)
}

// CreateAnswer mocks base method.
func (m *MockAnswerRepository) CreateAnswer(ctx context.Context, tx any, questionID int, text string, isCorrect bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnswer", ctx, tx, questionID, text, isCorrect)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAnswer indicates an expected call of CreateAnswer.
func (mr *MockAnswerRepositoryMockRecorder) CreateAnswer(ctx, tx, questionID, text, isCorrect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnswer", reflect.TypeOf((*MockAnswerRepository)(nil).CreateAnswer), ctx, tx, questionID, text, isCorrect)
}

// DeleteAnswer mocks base method.
func (m *MockAnswerRepository) DeleteAnswer(ctx context.Context, answerID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnswer", ctx, answerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnswer indicates an expected call of DeleteAnswer.
func (mr *MockAnswerRepositoryMockRecorder) DeleteAnswer(ctx, answerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnswer", reflect.TypeOf((*MockAnswerRepository)(nil).DeleteAnswer), ctx, answerID)
}

// GetAnswer mocks base method.
func (m *MockAnswerRepository) GetAnswer(ctx context.Context, answerID int) (entities.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnswer", ctx, answerID)
	ret0, _ := ret[0].(entities.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnswer indicates an expected call of GetAnswer.
func (mr *MockAnswerRepositoryMockRecorder) GetAnswer(ctx, answerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnswer", reflect.TypeOf((*MockAnswerRepository)(nil).GetAnswer), ctx, answerID)
}

// GetAnswersByQuestionIDs mocks base method.
func (m *MockAnswerRepository) GetAnswersByQuestionIDs(ctx context.Context, questionIDs []int) ([]entities.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnswersByQuestionIDs", ctx, questionIDs)
	ret0, _ := ret[0].([]entities.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnswersByQuestionIDs indicates an expected call of GetAnswersByQuestionIDs.
func (mr *MockAnswerRepositoryMockRecorder) GetAnswersByQuestionIDs(ctx, questionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnswersByQuestionIDs", reflect.TypeOf((*MockAnswerRepository)(nil).GetAnswersByQuestionIDs), ctx, questionIDs)
}

// GetQuizAnswers mocks base method.
func (m *MockAnswerRepository) GetQuizAnswers(ctx context.Context, questionID int) ([]entities.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuizAnswers", ctx, questionID)
	ret0, _ := ret[0].([]entities.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuizAnswers indicates an expected call of GetQuizAnswers.
func (mr *MockAnswerRepositoryMockRecorder) GetQuizAnswers(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuizAnswers", reflect.TypeOf((*MockAnswerRepository)(nil).GetQuizAnswers), ctx, questionID)
}

// UpdateAnswer mocks base method.
func (m *MockAnswerRepository) UpdateAnswer(ctx context.Context, answerID int, data dto.UpdateAnswerDTO) (entities.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnswer", ctx, answerID, data)
	ret0, _ := ret[0].(entities.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAnswer indicates an expected call of UpdateAnswer.
func (mr *MockAnswerRepositoryMockRecorder) UpdateAnswer(ctx, answerID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnswer", reflect.TypeOf((*MockAnswerRepository)(nil).UpdateAnswer), ctx, answerID, data)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, username, password_hash string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, username, password_hash)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, username, password_hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, username, password_hash)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(ctx context.Context, username string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), ctx, username)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionRepository) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepositoryMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepository)(nil).Delete), ctx, token)
}

// DeleteQuizSession mocks base method.
func (m *MockSessionRepository) DeleteQuizSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuizSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuizSession indicates an expected call of DeleteQuizSession.
func (mr *MockSessionRepositoryMockRecorder) DeleteQuizSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuizSession", reflect.TypeOf((*MockSessionRepository)(nil).DeleteQuizSession), ctx, sessionID)
}

// Get mocks base method.
func (m *MockSessionRepository) Get(ctx context.Context, token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionRepositoryMockRecorder) Get(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionRepository)(nil).Get), ctx, token)
}

// GetQuizSession mocks base method.
func (m *MockSessionRepository) GetQuizSession(ctx context.Context, sessionID string) (*entities.QuizSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuizSession", ctx, sessionID)
	ret0, _ := ret[0].(*entities.QuizSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuizSession indicates an expected call of GetQuizSession.
func (mr *MockSessionRepositoryMockRecorder) GetQuizSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuizSession", reflect.TypeOf((*MockSessionRepository)(nil).GetQuizSession), ctx, sessionID)
}

// SaveQuizSession mocks base method.
func (m *MockSessionRepository) SaveQuizSession(ctx context.Context, session entities.QuizSession, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveQuizSession", ctx, session, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveQuizSession indicates an expected call of SaveQuizSession.
func (mr *MockSessionRepositoryMockRecorder) SaveQuizSession(ctx, session, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveQuizSession", reflect.TypeOf((*MockSessionRepository)(nil).SaveQuizSession), ctx, session, ttl)
}

// Set mocks base method.
func (m *MockSessionRepository) Set(ctx context.Context, token string, userID int, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, token, userID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSessionRepositoryMockRecorder) Set(ctx, token, userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSessionRepository)(nil).Set), ctx, token, userID, ttl)
}

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
	isgomock struct{}
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// WithinTransaction mocks base method.
func (m *MockTransactionManager) WithinTransaction(ctx context.Context, fn func(pgx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithinTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithinTransaction indicates an expected call of WithinTransaction.
func (mr *MockTransactionManagerMockRecorder) WithinTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithinTransaction", reflect.TypeOf((*MockTransactionManager)(nil).WithinTransaction), ctx, fn)
}
